### ISSUE TITLE
institution_id registration of UBA-CIMA-IFAECI

### ISSUE THREAD

**Issue by LluisFB** [WCRP-CORDEX/cordex-cmip6-cv#108]
### institution_id

UBA-CIMA-IFAECI

### institution

UBA [Universidad de Buenos Aires, C. A. Buenos Aires (CABA), Argentina]; CIMA [Centro de Investigaciones del Mar y la Atmosfera, C. A. Buenos Aires (CABA), Argentina]; IFAECI [Instituto Franco-Argentino sobre Estudios de Clima y sus Impactos, C. A. Buenos Aires (CABA), Argentina]

**Comment by jesusff** [comment]
I suggest to code this as a partnership:

> UBA [Universidad de Buenos Aires, Buenos Aires, Argentina]; CIMA [Centro de Investigaciones del Mar y la Atmosfera, Buenos Aires, Argentina]; IFAECI [Instituto Franco-Argentino sobre Estudios de Clima y sus Impactos, Buenos Aires, Argentina] 

I simplified the city name to just Buenos Aires, not sure whether it requires further disambiguation within Argentina. We can also keep the original Autonomous City (C. A.) in front and/or the acronym (CABA) if you like. There is no need for detailed postal address though, just basic disambiguation.

**Comment by jesusff** [comment]
OK, no problem. Please, check the initial post, which I updated according to this.

**Comment by LluisFB** [comment]
Perfect, thanks.

**Comment by gnikulin** [comment]
@LluisFB could you also register  respective `source_id` ?

**Comment by LluisFB** [comment]
Hi Grigory,

Absolutely, but sorry, I am absolutely lost in this vocabulary. If I understand 'source_id' corresponds to 'model identifier (acronym)'. In my case I might be using different models (versions from each too), so I am quite lost. I mostly could be using either WRF or RegIPSL (Regional Earth System Model from the IPSL). WRF I guess, is already registered (at least WRF451Q which corresponds to the version used in CORDEX FPS URB RCC [experiment also registered]). But I am pretty sure that RegIPSL might not be registered (is the dynamical coupling of WRF [atmosphere], ORCHIDEE [land], NEMO [ocean]).
I will really appreciate if you can tell me how to proceed.
Lluís

**Comment by gnikulin** [comment]
Hi Lluís,

yes `source_id` is RCM name or acronym. If you are going to use WRF451Q,  indeed, this RCM has already been registered. Perhaps we need to update `institutions_id` associated with WRF451Q by adding UBA-CIMA-IFAECI @jesusff  ?

**Comment by gnikulin** [comment]
One institution can run several RCMs no any problem here but all of them must be registered and attached to at least one institution. I mean if we take a RCM it should be clear what institutions use this specific RCMs and the opposite what RCMs are used by a specific institution. Both `institution_id` and `source_id` are part of the Data Reference Syntax (DRS ) and provide an unique combination used in file names, global attributes and ESGF directory structure.  This information is also needed for the [CORDEX simulations status](https://github.com/WCRP-CORDEX/simulation-status?tab=readme-ov-file). Now I see only CIMA and RegIPSL for SAM-25 in the simulation list, should be updated after the registration.

**Comment by LluisFB** [comment]
Ok, I see and understand now.

I will proceed, sorry for bothering.

Thanks,

Lluís

**Comment by LluisFB** [comment]
@gnikulin , sorry, how to proceed to update the source_id? I thought should be an active link (like the one for new institution), but I am not finding it. 
How it is supposed I should do it?
Thanks, 
Lluís

**Comment by gnikulin** [comment]
you can find a link and instructions for "New source_id (i.e. model)" here  https://github.com/WCRP-CORDEX/cordex-cmip6-cv

**Comment by gnikulin** [comment]
just below "New institution_id"

**Comment by jesusff** [comment]
Hi @LluisFB,

just to mention that the rest of the WRF groups still need to register. WRF451Q is there as an example of the configuration that we will use in EURO-CORDEX (https://github.com/CORDEX-WRF-community/euro-cordex-cmip6). For the moment, it is only attached to the consortium we have with BCCR (BCCR-UCAN), but this will be extended with other groups running this config.

Of course, if you plan to run exactly this config over e.g. SAM-25, you can add your `institution_id` under WRF451Q. Otherwise, just create a new `source_id`. Note that this is not the configuration used in CORDEX FPS URB RCC; that one is called WRF451R in Stage-0 (https://github.com/CORDEX-WRF-community/fps-urb-rcc/tree/main/STAGE-0). WRF451R is not yet registered here, as simulations for this stage will not likely be published on ESGF. We can discuss all this internally with the WRFcom.

**Comment by LluisFB** [comment]
Thank you to you Grigory and Jesus,

Now I fully understand, so in such case, I will need to add the source_id from RegIPSL. These will be the simulations that we should charge into the ESGF-CORDEX as promised.

Lluís

**Comment by jesusff** [comment]
The discussion continues with the `source_id` registration in #122 , but I think the `institution_id` is already clear

**Comment by gnikulin** [comment]
yes, the institution can be registered
