### ISSUE TITLE
institution_id registration - update UQ-DES to UQ-DEC

### ISSUE THREAD

**Issue by sdesrosiers1989** [WCRP-CORDEX/cordex-cmip6-cv#111]
### institution_id

UQ-DEC

### institution

UQ [University of Queensland, Brisbane, Australia]; DEC [Department of Energy and Climate, Brisbane, Australia]

**Comment by larsbuntemeyer** [comment]
Thanks @sdesrosiers1989 , this i an update to #39. I'll check and then update the replace your institute_id `UQ-DES` with `UQ-DEC`.
