### ISSUE TITLE
institution_id registration of HCLIMcom-METNo

### ISSUE THREAD

**Issue by doblerone** [WCRP-CORDEX/cordex-cmip6-cv#112]
### institution_id

HCLIMcom-METNo

### institution

HARMONIE Climate Modelling Community (HCLIMcom) partner: Norwegian Meteorological Institute (METNo), Oslo, Norway

**Comment by gnikulin** [comment]
looks fine and can be registered

**Comment by gnikulin** [comment]
simulations are already in the downscaling plan

**Comment by jesusff** [comment]
/register

yes, looks good
