### ISSUE TITLE
institution_id registration of IRD-MF

### ISSUE THREAD

**Issue by Hanhle-CLIPSSA** [WCRP-CORDEX/cordex-cmip6-cv#136]
### institution_id

IRD-MF

### institution

IRD [Institut de Recherche pour le Developpement, Noumea (New Caledonia), France]; MF [Meteo France, Toulouse, France]

**Comment by jesusff** [comment]
@Hanhle-CLIPSSA, shall we add New Caledonia to the city name to better locate it geographically? "Noumea (New Caledonia), France"

Is there a better region/province name we could use?

**Comment by Hanhle-CLIPSSA** [comment]
@jesusff  Thank you so much for your comment. I think it is reasonable to put the name as you suggested. Cheers./

**Comment by jesusff** [comment]
Thanks, I modified the original post accordingly for registration. Looks good to me.

**Comment by jesusff** [comment]
/register

This was pending. I think we can go on

**Comment by jesusff** [comment]
Sorry, I missed the accented character in _D**é**veloppement_. I removed it in the final submission according to the decisions in  #34
