### ISSUE TITLE
source_id registration of CNRM-ALADIN64P1

### ISSUE THREAD

**Issue by Hanhle-CLIPSSA** [WCRP-CORDEX/cordex-cmip6-cv#137]
### label

CNRM-ALADIN64P1

### label_extended

CNRM-ALADIN regional climate model, version 6.4 P1

### source_id

CNRM-ALADIN64P1

### source_type

ARCM

### release_year

2023

### activity_participation

DD

### institution_id

IRD-MF

### further_info_url

http://www.umr-cnrm.fr/spip.php?article125&lang=en

### What license do you choose?

CC BY 4.0

**Comment by gnikulin** [comment]
@Hanhle-CLIPSSA,  

- just to check that CNRM-ALADIN64P1 is another version of CNRM-ALADIN64 and differs from CNRM-ALADIN64E1 which has already been registered by CNRM-MF ?
- I would recommend to change `label_extended` to `CNRM-ALADIN regional climate model, version 6.4 P1` to be consistent with CNRM-ALADIN64E1
- could you also update the CORDEX simulation status (https://github.com/WCRP-CORDEX/simulation-status) by adding information about your planned simulations ?

**Comment by jesusff** [comment]
Also, the further_info_url is the same as for CNRM-ALADIN64E1. If there is no specific public resource describing CNRM-ALADIN64P1 or its differences with respect to CNRM-ALADIN64E1, could you briefly explain here the major overall differences? Thank you!

**Comment by Hanhle-CLIPSSA** [comment]
@gnikulin : Thank you for your comments! 
1/ Yes. It is another version of CNRM-ALADIN64 that includes new physics options.
2/ I agree with your suggestion. It looks so much better. 
3/ I will add info for our simulations. 
Thank you so much !

**Comment by Hanhle-CLIPSSA** [comment]
@jesusff : At this stage, we only have the technical report from Jean-Francois Geremy- the developer. So I put the url of CNRM as general info. This version has new physics options. That includes the modification of turbulence, possible local non-conservation of total energy in physics, and a correction of the orographic gravity wave pattern. Besides, we have model tuning that is dedicated to Pacific regions. Thank you for your comments!

**Comment by jesusff** [comment]
Sorry, this was forgotten for a long time here. Could you add here the simulations you plan to carry out with this model?: https://github.com/WCRP-CORDEX/simulation-status

**Comment by jesusff** [comment]
/register

Plans have been added in https://github.com/WCRP-CORDEX/simulation-status/issues/42. Thank you!
