### ISSUE TITLE
institution_id registration of Deutscher Wetterdienst

### ISSUE THREAD

**Issue by csteger** [WCRP-CORDEX/cordex-cmip6-cv#144]
### institution_id

CLMcom-DWD

### institution

Climate Limited-area Modelling Community (CLMcom) partner: Deutscher Wetterdienst, Offenbach am Main, Germany

**Comment by csteger** [comment]
In the CLM Community we will use one Modellversion to produce the CORDEX simulations (at least for EURO-CORDEX and uncoupled). Several institions will contribute. We decdided to use CLMcom-INSTITUTION as instition_id to make the contributions of the different institutions more visible.

**Comment by csteger** [comment]
Hi Chus, 
Thanks for the comment. Good suggestion. I will change it.

**Comment by csteger** [comment]
Not sure if I can change it here. It should now be: 
institution_id: CLMcom-DWD
institution: Climate Limited-area Modelling Community (CLMcom) partner: Deutscher Wetterdienst, 63067 Offenbach, Germany

Can you change it or should I open a new issue?

**Comment by jesusff** [comment]
yes, we can just change the original post in the issue. I did it, but you should also be able to do it in the three dot menu (and then, Edit) on the upper right corner of the post.

We are not collecting postal codes. If Offenbach needs disambiguation within Germany, we could add the Land in parenthesis, as in `Offenbach (Hesse), Germany`. Does this sound OK?

**Comment by csteger** [comment]
Okay. I add Offenbach am Main. That is the official name.

**Comment by jesusff** [comment]
/register

Looks good. Thanks
