### ISSUE TITLE
Grid description in case of variable dependent remapping methods

### ISSUE THREAD

**Issue by sol1105** [WCRP-CORDEX/cordex-cmip6-cv#149]
I have a question regarding the global attribute `grid`. We plan to remap extensive quantities conservatively, and else with the nearest neighbor method. What do you suggest as the `grid` description? I could think of 2 options:

### 1
> Rotated-pole latitude-longitude with 0.11 degree grid spacing, interpolated by nearest neighbor remapping from the original unstructured icosahedral ICON grid R13B05 (~12.1 km).

And specifying a variable comment for all variables where this is not the case.

### 2

> Rotated-pole latitude-longitude with 0.11 degree grid spacing, interpolated by either second order conservative (extensive quantities) or nearest neighbor remapping (intensive quantities) from the original unstructured icosahedral ICON grid R13B05 (~12.1 km).

That would be my preference. If this is not sufficient, we could additionally include a variable comment denoting the actually used remapping method for each variable.

**Comment by larsbuntemeyer** [comment]
Both should be fine with the archiving specs, so i suggest, you can go with your preference. Of course, if your workflow allows it, you are welcome to include variable specific interpolation info, e.g., if it's an *extensive* or *intensice* quantity.

**Comment by sol1105** [comment]
Thank you for the quick reply :)

We will discuss whether to additionally include the specific interpolation info as variable comment. Workflow-wise it is possible, though a little more effort.

**Comment by jesusff** [comment]
Maybe I'm missing something here but, why not have for each variable the corresponding `grid` attribute with the interpolation that was really applied?

**Comment by larsbuntemeyer** [comment]
It's just that I am also used to having one dataset json file per experiment as described in the [API](https://cmor.llnl.gov/mydoc_cmor3_api/#cmor_dataset_json) and not making it dependent on the variable_id. However, there is also [set_cur_dataset_attribute](https://cmor.llnl.gov/mydoc_cmor3_api/#cmor_set_cur_dataset_attribute) which might be useful in this case to set some variable_id specific attributes during the workflow.

**Comment by sol1105** [comment]
Yes, it would be possible, but in our workflow more effort than the general `grid` description and specification via variable comment (which is also persistent when eg. merging multiple variables into one xarray dataset later on).
