### ISSUE TITLE
institution_id registration of MOHC (Met Office Hadley Centre)

### ISSUE THREAD

**Issue by gredmond-mo** [WCRP-CORDEX/cordex-cmip6-cv#163]
### institution_id

MOHC

### institution

Met Office Hadley Centre, Exeter, United Kingdom

**Comment by jesusff** [comment]
Duplicate of #49 

@gredmond-mo do you want to update the entry for MOHC? The only difference I see in this new request is the expanded form "United Kingdom" instead of "UK"

**Comment by gredmond-mo** [comment]
Hi Jesus, no sorry, this is a duplicate, I must have been looking at an old version of the institution CV in which MOHC wasn't included. This can be closed as a duplicate.

**Comment by jesusff** [comment]
no worries :-) I close it, then
