### ISSUE TITLE
New registration id : CLMcom-CMCC

### ISSUE THREAD

**Issue by marioRaffa** [WCRP-CORDEX/cordex-cmip6-cv#169]
### institution_id

CLMcom-CMCC

### institution

Climate Limited-area Modelling Community (CLMcom) partner:  Euro-Mediterranean Center on Climate Change (CMCC Foundation), Caserta, Italy

**Comment by jesusff** [comment]
/register

Thank you, Mario. This follows other CLMcom groups, so looks good to me
