### ISSUE TITLE
source_id registration of KNMI-RACMO23E

### ISSUE THREAD

**Issue by erikvanmeijgaard** [WCRP-CORDEX/cordex-cmip6-cv#171]
### label

RACMO23E

### label_extended

The KNMI Regional Climate Model RACMO, version 23E 

### source_id

RACMO23E

### source_type

ARCM

### release_year

2022

### activity_participation

DD

### institution_id

KNMI

### further_info_url

https://cdn.knmi.nl/system/data_center_publications/files/000/071/902/original/KNMI23_climate_scenarios_scientific_report_WR23-02.pdf

### What license do you choose?

CC BY 4.0

**Comment by jesusff** [comment]
Thank you, Erik. I assume the model description is the one found in section 2.4 of the `further_info_url` provided (KNMI'23 scenarios). The final E refers to this specific configuration for Europe, right? (as in the previous CORDEX simulations with RACMO22E and RACMO22T)

**Comment by erikvanmeijgaard** [comment]
Indeed, Jesus, section 2.4 it should be. Perhaps it can be stated "section 2.4 in further_info_url" instead of "further_info_url" only, I don't know if that feasible and/or desirable.

In the previous set of CORDEX simulations I had introduced  RACMO22T for the AFR-50 runs, and RACMO21P for the ANT-50 simulations. So, yes, E can be seen as European, or more generally, mid-latitude. I don't know, though if there will at some point be CORDEX-simulation with RACMO23T and/or RACMO23P. But, in essence, RACMO23E is the natural successor of RACMO22E.

**Comment by jesusff** [comment]
Perfect. I think it is fine. This explanation can also be found if somebody looks for RACMO here in the future. The `further_info_url` should actually be a URL, so it can stay as is or we could point it directly to https://cdn.knmi.nl/system/data_center_publications/files/000/071/902/original/KNMI23_climate_scenarios_scientific_report_WR23-02.pdf#section.2.4 . If you have later on a more detailed reference, we can always update it.

**Comment by erikvanmeijgaard** [comment]
Okee, let's keep the URL as it is now. When people scroll through the document behind the URL they will quickly see in the contents page where to find the RACMO description. Or they already have read the explanation above.
