### ISSUE TITLE
institution_id registration of CLMcom-GERICS

### ISSUE THREAD

**Issue by larsbuntemeyer** [WCRP-CORDEX/cordex-cmip6-cv#177]
### institution_id

CLMcom-GERICS

### institution

Climate Limited-area Modelling Community (CLMcom) partner: Climate Service Center Germany, Hamburg, Germany

**Comment by larsbuntemeyer** [comment]
This is required for UDAG.

**Comment by jesusff** [comment]
Looks good.

@csteger, regarding UDAG, in the simulation status (I know you are currently updating it) there are at the moment simulations assigned to an institution CLMcom-UDAG:

https://github.com/WCRP-CORDEX/simulation-status/blob/449316215dbfd6be65aa35ede210ca56a91c9cbe/CMIP6_downscaling_plans.csv#L284

As far as I understand it (https://github.com/WCRP-CORDEX/simulation-status/issues/11), UDAG is actually a project with several institutions involved. We could manage this with a EUR-12 [experiment](https://wcrp-cordex.github.io/simulation-status/CORDEX_CMIP6_status_by_experiment.html#EUR-12), i.e. adding a tag #UDAG to the simulations that belong to it. This would not put the UDAG naming into the DRS (filenames or mandatory file metadata), though, if this is what you intend.

**Comment by csteger** [comment]
Hi Chus, 
The CLMcom-UDAG was an early idea that will not use. There will be no CLMcom-UDAG entry in the list once I have updated it. We will use CLMcom-$INSTITUTION (e.g. CLMcom-DWD, CLMcom-KIT, ...). 

If a tag #UDAG is possible without much overhead, we can do it. It would then be easy to find the runs that were produced in the project. 

Christian

**Comment by jesusff** [comment]
Perfect, thanks. It is just a matter of adding #UDAG to the comment field in the CSV simulation list 

@larsbuntemeyer, this GERICS entry looks good, so I think we can register

**Comment by larsbuntemeyer** [comment]
Thanks for your input!
