### ISSUE TITLE
institution_id registration of BSH

### ISSUE THREAD

**Issue by WibkeDuesterhoeft** [WCRP-CORDEX/cordex-cmip6-cv#180]
### institution_id

DWD-BSH

### institution

DWD [Deutscher Wetterdienst, Offenbach am Main, Germany]; BSH [Bundesamt fuer Seeschifffahrt und Hydrographie, Hamburg, Germany]

**Comment by jesusff** [comment]
Thank you for registering your institution. We'll need to adapt the naming to skip the umlaut (fur or fuer, #34) 

Is ROAM2 the model you will be using? please, register it by opening an issue [here](https://github.com/WCRP-CORDEX/cordex-cmip6-cv/issues/new?assignees=&labels=Register+source-id&projects=&template=source_id.yaml&title=source_id+registration+of+...) and provide a summary of your planned simulations to include you in the summary tables [here](https://github.com/WCRP-CORDEX/simulation-status).

Thank you!

**Comment by WibkeDuesterhoeft** [comment]
Thank you for the reply.

Shall I adapt the umlaut in a new request or is this done automatically by you?

The model we are jointly working on with DWD  (ROAM-NBS) will be added by DWD together with the summary of planned simulations.

Best regards
Wikbe Düsterhöft-Wriggers

Wibke Düsterhöft-Wriggers
DAS-Basisdienst
Bundesamt für Seeschifffahrt und Hydrographie
***@***.***



Von: Jesus Fernandez ***@***.***>
Gesendet: Freitag, 27. September 2024 21:22
An: WCRP-CORDEX/cordex-cmip6-cv ***@***.***>
Cc: Wibke Düsterhöft-Wriggers ***@***.***>; Author ***@***.***>
Betreff: Re: [WCRP-CORDEX/cordex-cmip6-cv] institution_id registration of Bundesamt für Seeschifffahrt und Hydrographie for ROAM2 (Issue #180)


Thank you for registering your institution. We'll need to adapt the naming to skip the umlaut (fur or fuer, #34<https://github.com/WCRP-CORDEX/cordex-cmip6-cv/issues/34>)

Is ROAM2 the model you will be using? please, register it by opening an issue here<https://github.com/WCRP-CORDEX/cordex-cmip6-cv/issues/new?assignees=&labels=Register+source-id&projects=&template=source_id.yaml&title=source_id+registration+of+...> and provide a summary of your planned simulations to include you in the summary tables here<https://github.com/WCRP-CORDEX/simulation-status>.

Thank you!

**Comment by jesusff** [comment]
Perfect, thank you. I updated the umlaut (let me know if you'd prefer "fur", instead).

I understand you will split the simulations with DWD (e.g. by nesting into different GCMs), so you will register independently. If you prefer to register a BSH-DWD partnership for these simulations, this is also possible.

**Comment by WibkeDuesterhoeft** [comment]
Thank you, is the umlaut actually changed now, since I still see "für" in the request?

Since we changed our name of the model from ROAM2 to ROAM-NBS after I submitted the first request, this got confusing. 

We are planning on only running one set of simulations as a BSH-DWD partnership where the DWD has the lead and will add the source_id and simulation plans. Is this ok, if we request single institution_id or do we need to do a partner institution_id ?

**Comment by WibkeDuesterhoeft** [comment]
Thank you, is the umlaut actually changed now, since I still see "für" in the request?

Since we changed our name of the model from ROAM2 to ROAM-NBS after I submitted the first request, this got confusing.

We are planning on only running one set of simulations as a BSH-DWD partnership where the DWD has the lead and will add the source_id and simulation plans. Is this ok, if we request single institution_id or do we need to do a partner institution_id ?

-----Ursprüngliche Nachricht-----
Von: Jesus Fernandez ***@***.***> 
Gesendet: Dienstag, 1. Oktober 2024 11:28
An: WCRP-CORDEX/cordex-cmip6-cv ***@***.***>
Cc: Wibke Düsterhöft-Wriggers ***@***.***>; Author ***@***.***>
Betreff: Re: [WCRP-CORDEX/cordex-cmip6-cv] institution_id registration of Bundesamt für Seeschifffahrt und Hydrographie for ROAM2 (Issue #180)

Perfect, thank you. I updated the umlaut (let me know if you'd prefer "fur", instead).

I understand you will split the simulations with DWD (e.g. by nesting into different GCMs), so you will register independently. If you prefer to register a BSH-DWD partnership for these simulations, this is also possible.

**Comment by jesusff** [comment]
Dear Wibke, I commented on the partnership with DWD in #186. Please, have a look, but we can continue the clarifications on the institutions in this issue, and let that one to discuss the model. I changed the umlaut in the text of your first post, which will go to the registry automatically. The title of the post is not very important.

One potential partnership registration would be:
```
institution_id = CLMcom-DWD-BSH
institution = CLMcom-DWD [Climate Limited-area Modelling Community (CLMcom) partner: Deutscher Wetterdienst, Offenbach am Main, Germany]; BSH [Bundesamt fuer Seeschifffahrt und Hydrographie, Hamburg, Germany]
```

**Comment by WibkeDuesterhoeft** [comment]
Dear Jesus, thank you for the clarifications. Together with Vera we decided that the best option in our case is to chose
institution_id = DWD-BSH
and then the institution would be
institution = DWD [Deutscher Wetterdienst, Offenbach am Main, Germany]; BSH [Bundesamt fuer Seeschifffahrt und Hydrographie, Hamburg, Germany]

**Comment by jesusff** [comment]
/register

Thank you. This looks good
