### ISSUE TITLE
institution_id registration of RMIB-UGent

### ISSUE THREAD

**Issue by kobebryant432** [WCRP-CORDEX/cordex-cmip6-cv#200]
### institution_id

RMIB-UGent

### institution

RMIB [Royal Meteorological Institute of Belgium, Brussels, Belgium]; UGent [Ghent University, Ghent, Belgium]

**Comment by jesusff** [comment]
Thank you for the input, Kobe. This seems like a partnertship, so you should separate the expansion of each institution. Also, provide the city. How do you see something along these lines?:
```
institution = "RMIB [Royal Meteorological Institute of Belgium, Brussels, Belgium]; UGENT [Ghent University, Ghent, Belgium]"
```

**Comment by kobebryant432** [comment]
Hi Jesus, That seems fine. Maybe UGENT should be UGent instead as Gent is not an acronym? 
This we result in:
```bash
institution = "RMIB [Royal Meteorological Institute of Belgium, Brussels, Belgium]; Ugent [Ghent University, Ghent, Belgium]"
```
and 
```bash
institution _id = "RMIB-Ugent"
```

This would have to also be changed in #207 but in https://github.com/WCRP-CORDEX/simulation-status/issues/38 this is already correct.

**Comment by jesusff** [comment]
/register

Looks good, thank you
