### ISSUE TITLE
source_id registration of ALARO1-SFX

### ISSUE THREAD

**Issue by kobebryant432** [WCRP-CORDEX/cordex-cmip6-cv#207]
### label

ALARO1-SFX

### label_extended

ALARO1-SFX regional climate model, ALARO1 (ALadin-AROme) cycle 43T2 with SURFEX v8.0

### source_id

ALARO1-SFX

### source_type

ARCM

### release_year

2024

### activity_participation

DD

### institution_id

RMIB-UGent

### further_info_url

https://gmd.copernicus.org/articles/11/257/2018/

### What license do you choose?

CC BY 4.0

**Comment by kobebryant432** [comment]
See also #200

**Comment by jesusff** [comment]
/register

OK, I updated the institution according to #200 and already merged https://github.com/WCRP-CORDEX/simulation-status/issues/38
