### ISSUE TITLE
institution_id registration of CLMcom-ETH

### ISSUE THREAD

**Issue by mjaehn** [WCRP-CORDEX/cordex-cmip6-cv#219]
### institution_id

CLMcom-ETH

### institution

Climate Limited-area Modelling Community (CLMcom) partner: Federal Institute of Technology Zurich, Zurich, Switzerland

**Comment by jesusff** [comment]
Dear Michael, please, check my edit of your institution to include the "Climate Limited-area Modelling Community (CLMcom) partner" part, as the rest of the community (#144). See https://wcrp-cordex.github.io/cordex-cmip6-cv/CORDEX-CMIP6_institution_id.html for other examples.

Other than that, it looks fine to me.

**Comment by mjaehn** [comment]
@jesusff LGTM
