### ISSUE TITLE
institution_id registration of Helmholtz-Zentrum Hereon

### ISSUE THREAD

**Issue by GeyerB** [WCRP-CORDEX/cordex-cmip6-cv#227]
### institution_id

CLMcom-Hereon

### institution

Climate Limited-area Modelling Community (CLMcom) partner: Helmholtz-Zentrum Hereon, Geesthacht, Germany

**Comment by GeyerB** [comment]
The right entry would have been:
Climate Limited-area Modelling Community (CLMcom) partner: Helmholtz-Zentrum Hereon, Geesthacht, Germany

**Comment by jesusff** [comment]
/register

looks good, thanks!
