### ISSUE TITLE
institution_id registration of CLMcom-BTU

### ISSUE THREAD

**Issue by awill-btu** [WCRP-CORDEX/cordex-cmip6-cv#228]
### institution_id

CLMcom-BTU

### institution

Climate Limited-area Modelling Community (CLMcom) partner: Brandenburgische Technische Universitaet  Cottbus-Senftenberg, Cottbus, Germany

**Comment by larsbuntemeyer** [comment]
Thanks @awill-btu i only expanded the 'ä' into 'ae' since we avoid special characters. Otherwise it looks fine!

**Comment by jesusff** [comment]
/register

Thank you for the input, Andreas. Looks good
