### ISSUE TITLE
institution_id registration of CLMcom-KUL

### ISSUE THREAD

**Issue by Ivanderkelen** [WCRP-CORDEX/cordex-cmip6-cv#238]
### institution_id

CLMcom-KUL

### institution

Climate Limited-area Modelling Community (CLMcom) partner: KU Leuven, Leuven, Belgium

**Comment by jesusff** [comment]
Thank you!

I updated the institution to include the CLM community as the rest of the partners. Please, consider expanding the KU acronym in the institution

**Comment by Ivanderkelen** [comment]
Thanks! We prefer to keep KU Leuven as such, as it is the official name (they abandoned the 'Katholieke Universiteit' a couple of years ago.

**Comment by jesusff** [comment]
/register

Perfect. Let's go for it, then
