### ISSUE TITLE
source_id registration of CCLM6-0-1-URB-ESG

### ISSUE THREAD

**Issue by Ivanderkelen** [WCRP-CORDEX/cordex-cmip6-cv#239]
### label

CCLM6-0-1-URB-ESG

### label_extended

COSMO model in climate mode (COSMO-CLM), Version 6.0 clm 1 with Urban Parametrization and ECOCLIMAP-Second Generation land cover

### source_id

CCLM6-0-1-URB-ESG

### source_type

ARCM

### release_year

2021

### activity_participation

DD

### institution_id

CLMcom-KUL

### further_info_url

https://www.clm-community.eu/COSMO-CLM/Overview/

### What license do you choose?

CC BY 4.0

**Comment by Ivanderkelen** [comment]
Similar source_id to #216 of CMCC, but using ECOCLIMAP-Second Generation land cover dataset instead of the default GLOBCOVER (hence ESG)

@csteger

**Comment by jesusff** [comment]
Thank you, Inne. Looks good to me except we still need to clarify if you really have a dash between CCLM and the 6 in the CLM community (#216)

**Comment by csteger** [comment]
Hi Chus, Inne, 
in the CLM Community naming convention document there is no dash between CCLM and 6-0-1 (CCLM6-0-1): https://www.clm-community.eu/uploads/media/material/62ff9ff3-0d40-42fa-a552-021dd6eebf12/[20241121_CLM-Community_naming-convention_CORDEX.pdf](https://www.clm-community.eu/uploads/media/material/62ff9ff3-0d40-42fa-a552-021dd6eebf12/20241121_CLM-Community_naming-convention_CORDEX.pdf) 

But I didn't really think much about this. We could use dash in between, but we should make sure it is consistent for all source_ids. 

I already distributed the naming convention document, so other might already plan with CCLM6-0-1. Maybe it would be easier to go for this solution.

**Comment by Ivanderkelen** [comment]
Hi Christian, Chus, 

Thanks, I agree on leaving the dash out and edited the registration above to account for this. 

I updated the simulation status for the evaluation run (https://github.com/WCRP-CORDEX/simulation-status/issues/45) and will update the CMIP6 driven simulations in due course.

**Comment by jesusff** [comment]
/register

Thank you
