### ISSUE TITLE
frequencies with "Pt" in CORDEX-CMIP6_frequency.json

### ISSUE THREAD

**Issue by gnikulin** [WCRP-CORDEX/cordex-cmip6-cv#24]
Should all `*Pt` frequencies be removed form `CORDEX-CMIP6_frequency.json` since in CORDEX there are no variables that are archived as an average and as an instantaneous value ?

**Comment by sol1105** [comment]
I would not remove the `Pt`, to remain on one line with CMIP.
It also allows to identify if the variable is provided as an average or instantaneous value by looking at the filename. And one does not have to look into the file metadata (at the cell_methods or frequency attributes) for that. That is if the frequency is part of the DRS and not the CMOR table name, in which case a `CORDEX_1hrPt.json` would be necessary.

**Comment by gnikulin** [comment]
After some discussions there was an agreement to skip using "Pt" in CORDEX for the simplicity. We assume that some aspects of the CORDEX DRS can be different from CMIP6.  Until now I've never heard that there was any problem in CORDEX with the use of only `1hr`, `3hr` or `6hr` frequencies for both averages and instantaneous values. Separating variables between 2 tables for averages and instantaneous values is also an additional complexity. Now it's a table per frequency for all variables.  If the skipping of "Pt" doesn't lead to any critical problem may be we can keep the frequencies as before ?

**Comment by larsbuntemeyer** [comment]
Related to https://github.com/WCRP-CORDEX/cordex-cmip6-data-request/issues/24
The suffix is actually removed/not used in the data request table / cmor tables anymore but it is still in the CV, should probably be removed there too.

**Comment by gnikulin** [comment]
Yes, I just checked the tables. This "Pt" issue was discussed a while ago offline. We may wait a bit to see what others say.
