### ISSUE TITLE
values in CORDEX-CMIP6_activity_id.json

### ISSUE THREAD

**Issue by gnikulin** [WCRP-CORDEX/cordex-cmip6-cv#33]
We need to edit https://github.com/WCRP-CORDEX/cordex-cmip6-cv/blob/main/CORDEX-CMIP6_activity_id.json be deleting   "FPS" and "Adjust" and changing "RCM" to "DD". Can be simply ?

```json
{
  "activity_id": {
    "DD": "Dynamical Downsacling",
    "ESD": "Empirical Statistical Downscaling"
   }
 }
```

**Comment by larsbuntemeyer** [comment]
Ok, i'll try to close some issues including this during this week!

**Comment by jesusff** [comment]
OK, I updated this, but kept the original list format, since this impacts the way CMOR validates entries
https://github.com/WCRP-CORDEX/cordex-cmip6-cv/blob/b57012e00e28b54d148507b05605110220fe0085/CORDEX-CMIP6_activity_id.json#L1-L6
Also, there is currently no `activity` attribute, so the explanation would not be used in the DRS. This attribute would be helpful to clarify the meaning of the `activity_id`s, though (see #20). It could be more explicit, such as
```json
{
  "activity_id": {
    "DD": "Dynamical downscaling on standard CORDEX continental domains",
    "ESD": "Empirical-statistical downscaling on standard CORDEX continental domains"
   }
 }
```

**Comment by gnikulin** [comment]
I'm not sure about adding that these 2 activities are for the standard continental-scale CORDEX domains and would use "Dynamical downscaling" and "Empirical-statistical downscaling" as general definitions. Currently, there is no common  framework for sub-domains, only within different FPS, another challenge.

**Comment by gnikulin** [comment]
Yes, I agree that this case is only for the 14 continental-scale domains and in general we need to consider possible sub-domain activities. So currently we can use:  

```json
{
  "activity_id": {
    "DD": "Dynamical downscaling",
    "ESD": "Empirical-statistical downscaling"
   }
 }
``` 

ML-based downscaling methods can be another activity in this CV.

**Comment by larsbuntemeyer** [comment]
closed by [b57012](https://github.com/WCRP-CORDEX/cordex-cmip6-cv/commit/b57012e00e28b54d148507b05605110220fe0085)

**Comment by gnikulin** [comment]
My understanding is that we agreed on:

```json
{
  "activity_id": {
    "DD": "Dynamical downscaling",
    "ESD": "Empirical-statistical downscaling"
   }
 }
``` 
while the current [CMIP6_activity_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_activity_id.json) is still

```json
{ 
     "activity_id": [ 
         "DD", 
         "ESD" 
     ] 
 } 
``` 
or any CMOR-related issues ??
