### ISSUE TITLE
institution_id registration of UQ-DES

### ISSUE THREAD

**Issue by sdesrosiers1989** [WCRP-CORDEX/cordex-cmip6-cv#39]
### institution_id

UQ-DES

### institution

UQ [University of Queensland, Brisbane, Australia]; DES [Department of Environment and Science, Brisbane, Australia]

**Comment by larsbuntemeyer** [comment]
@gnikulin could you check? I think the format seems fine.

**Comment by gnikulin** [comment]
looks fine for me, @jesusff ?

**Comment by jesusff** [comment]
yes, looks good

**Comment by jesusff** [comment]
Hi Sarah, @sdesrosiers1989 

is this institution what is referred to as QLD-DES in the [simulation status](https://wcrp-cordex.github.io/simulation-status/CMIP6_downscaling_plans.html?search.search=des) and https://opus.nci.org.au/display/CMIP/CORDEX-CMIP6+datasets ?

Please, check the simulation status to confirm that everything is OK (except the institution_id if we need to change it)

**Comment by larsbuntemeyer** [comment]
@gnikulin @jesusff 
In #111 there is an update of the institution_id from `UQ-DES` to `UQ-DEC`. Should this also be updated in the simulation status?

**Comment by jesusff** [comment]
Yes, please, Sarah (@sdesrosiers1989 ) could you confirm how to proceed with the [simulation status](https://wcrp-cordex.github.io/simulation-status/CMIP6_downscaling_plans.html?search.search=des) that was registered for QLD-DES after https://opus.nci.org.au/display/CMIP/CORDEX-CMIP6+datasets ?

I'm afraid some simulations were not intended for CORDEX. There are different model versions: DES-CCAM-2105, DES-CCAM-2112, DES-CCAMoc-2112. Maybe registering these `source_id`s can clarify matters.

thank you!

**Comment by sdesrosiers1989** [comment]
Hi, yes, UQ-DES was QLD-DES in this table: https://opus.nci.org.au/display/CMIP/CORDEX-CMIP6+datasets
Our department name has changed and is now DEC, so we have to change to UQ-DEC. The table needs to be updated.

We've also changed our RCM names since that table was last updated to be consistent with how CSIRO is naming their model, since we're both running CCAM. I've already registered those names:
CCAMoc-v2112
CCAM-v2112
CCAM-v2105

**Comment by jesusff** [comment]
Ok, thank you, the simulation status was updated.

> I've already registered those names:
CCAMoc-v2112
CCAM-v2112
CCAM-v2105

Sorry, I cannot see them registered. You'd need to open a [`source_id` registration issue](https://github.com/WCRP-CORDEX/cordex-cmip6-cv/issues/new?assignees=&labels=Register+source_id&projects=&template=source_id.yaml&title=source_id+registration+of+...) for each of them. Thanks!

**Comment by larsbuntemeyer** [comment]
The renaming from `UQ-DES` to `UQ-DEC` has been handled in #111.

> I've already registered those names:
CCAMoc-v2112
CCAM-v2112
CCAM-v2105

@sdesrosiers1989 we can keep this discussion open if you need more help in registering your RCM ids.

**Comment by jesusff** [comment]
The `source_id`s registration was started. I close this discussion for the moment.
