### ISSUE TITLE
Update source type

### ISSUE THREAD

**Issue by sdesrosiers1989** [WCRP-CORDEX/cordex-cmip6-cv#40]
The UQ-DES team would like to update [source_type ](https://github.com/WCRP-CORDEX/cordex-cmip6-cv/blob/main/CORDEX-CMIP6_source_type.json) to have the option of :
AOGCM
with the description of:
"atmosphere-ocean global climate model including variable resolution"

**Comment by jesusff** [comment]
Thank you for your input, Sarah. The basic set of `source_type`s are still under debate in #20 (you can just skip the last entries of the long thread) with some suggestions coming from recent comments from the community to the second order draft of the DRS. Feel free to comment there if you have further input, as experience from the groups running variable-resolution global models is most welcome. 

We keep this issue open, anyway, until the basic set of `source_type`s is clarified

**Comment by larsbuntemeyer** [comment]
resolved by https://github.com/WCRP-CORDEX/cordex-cmip6-cv/commit/536ec66b68ad0f67bca4832f6dd4117c514d3f89
