### ISSUE TITLE
institution_id registration of CCCma 

### ISSUE THREAD

**Issue by YanjunJiao** [WCRP-CORDEX/cordex-cmip6-cv#41]
### institution_id

CCCma

### institution

Canadian Centre for Climate Modelling and Analysis, Environment and Climate Change Canada, Victoria (British Columbia), Canada

**Comment by gnikulin** [comment]
@jesusff  should be formatted with parenthesis ?

**Comment by jesusff** [comment]
Yes, I'd say to use: `..., Victoria, Canada` or `..., Victoria (BC), Canada` or `..., Victoria (British Columbia), Canada`
We are not after a full postal address here, just basic city disambiguation

**Comment by larsbuntemeyer** [comment]
I edited the issue body and went for the full `British Columbia` (as in `OURANOUS` id). @YanjunJiao if you are fine with this, we could register...

**Comment by gnikulin** [comment]
@YanjunJiao could you also provide information about your planned simulations in https://github.com/WCRP-CORDEX/simulation-status ?

**Comment by YanjunJiao** [comment]
> I edited the issue body and went for the full `British Columbia` (as in `OURANOUS` id). @YanjunJiao if you are fine with this, we could register...

@larsbuntemeyer I'm OK with the modification. Thanks
