### ISSUE TITLE
source_id registration of CanRCM5

### ISSUE THREAD

**Issue by YanjunJiao** [WCRP-CORDEX/cordex-cmip6-cv#42]
### label

CanRCM5-SN

### label_extended

Canadian Regional Climate Model version 5

### source_id

CanRCM5-SN

### source_type

ARCM

### release_year

2024

### activity_participation

DD

### institution_id

CCCma

### further_info_url

https://gitlab.com/cccma/canesm

### What license do you choose?

CC BY 4.0

**Comment by YanjunJiao** [comment]
@gnikulin This issue has been open for 4 months, could you please give us an update when CanRCM5 will registered

**Comment by gnikulin** [comment]
@YanjunJiao , the registration was formally open on April 12 when the CORDEX-CMIP6 archiving specifications [were released](https://cordex.org/2024/04/12/the-cordex-cmip6-archiving-specifications-for-dynamical-downscaling-now-published/), sorry for some miscommunication from our side. One requirement for the registration is to provide provide information about  planned simulations in t[he CORDEX-CMIP6 downscaling plan](https://github.com/WCRP-CORDEX/simulation-status). I see that [Scinocca](https://github.com/Scinocca)@  has already provided such info for CanRCM5 so now we can register it.

**Comment by larsbuntemeyer** [comment]
The url (https://gitlab.com/cccma/canrcm) is not reachable without login, are we ok with that?

**Comment by gnikulin** [comment]
obs, we assume a public webpage, @YanjunJiao do you have any public webpage describing CanRCM5?

**Comment by Scinocca** [comment]
@gnikulin apologies for the confusion regarding the URL for CanRCM5.  I will look into this and get back to you shortly.

**Comment by gnikulin** [comment]
@Scinocca the URL can be blank now and will be updated later

**Comment by Scinocca** [comment]
@gnikulin Yes that would work.  Do you need us to remove it from the post above?

**Comment by larsbuntemeyer** [comment]
Ok, i'll remove it for now! It won't end up in the CV table anyway.

**Comment by larsbuntemeyer** [comment]
@Scinocca I have the url now pointed to the public gitlab group of CCCma for now. If you have more specific link for CanRCM5, let me know!

**Comment by jesusff** [comment]
I wouldn't open so early the possibility to register a model without some openly available further info URL, even if it is a basic one. @Scinocca, any kind of resource would be OK, it doesn't need to be a very detailed description. It can be updated later on, when you have a better one. In a quick search, I found this video which I think is better than a private URL: https://mathtube.org/lecture/video/canadian-regional-climate-model . What do you think?

Also, in that video, it is suggested that you will use spectral nudging. If this is so, note the model name (source_id) must end in "-SN" (see the archiving specs at https://doi.org/10.5281/zenodo.10961069).

As a fallback option, you could even just describe in a response to this thread the basics of the model. This would be open and we could point directly to such brief description as initial `further_info_url`. In particular, it would be nice to clarify the main differences between between CanRCM5 and CRCM5-SN, as [these seem to be related](https://github.com/WCRP-CORDEX/cordex-cmip6-cv/issues/90#issuecomment-2067223677), but registration of CRCM5-SN is also pending the provision of a further_info_url.

**Comment by gnikulin** [comment]
I thought that we don't have constrains on blank `further_info_url` during the registration, although it's always good to have an URL from the beginning. Requesting to provide something might be not so good idea. The video found by @jesusff actually looks very good as a starting point.

Yes, if the spectral nudging is applied, `source_id` must include the "-SN" suffix to avoid any confusion.

**Comment by Scinocca** [comment]
Thanks, @larsbuntemeyer @jesusff and @gnikulin for the additional information. CanRCM5 and CRCM5 are completely separate efforts within the Canadian community.   While both models share a common semi-Lagrangian dynamical core, each uses an independent package of physical parameterizations.  As described in Scinocca et al. (2016; https://doi.org/10.1175/JCLI-D-15-0161.1), CanRCM shares the identical physics package as the atmospheric component, CanAM, of the global Canadian Earth-System Model, CanESM.  That physics package is developed in-house and is independent within the global and regional modelling communities, The complete codeset of the global and regional models are housed in one shared repository.  That repository can be referenced by the URL:  
https://gitlab.com/cccma/canesm.      
Please use this URL for CanRCM5. 

Apologies for missing the need for "-SN" in the source id.  Following the conventions outlined in https://doi.org/10.5281/zenodo.10961069, the model should have a source_id of "CanRCM5-SN".  I will ask my colleague @YanjunJiao who created this issue to make the modification later today.

Please let me know if you need any additional information.

**Comment by gnikulin** [comment]
@Scinocca it sounds fine, basically it's up to the CORDEX modelling groups to provide the "best" URL :-)

**Comment by jesusff** [comment]
Perfect. Fine for me as well. I already modified the first post accordingly

**Comment by larsbuntemeyer** [comment]
Thanks @Scinocca for all additional info! I'll correct it in the CV!

**Comment by gnikulin** [comment]
the CV can be updated now and that's all ?

**Comment by gnikulin** [comment]
the CV has  been updated so we can close this issue ?
