### ISSUE TITLE
institution_id registration of Bureau of Meteorology

### ISSUE THREAD

**Issue by chunhsusu** [WCRP-CORDEX/cordex-cmip6-cv#44]
### institution_id

BOM

### institution

Bureau of Meteorology, Melbourne, Australia

**Comment by gnikulin** [comment]
looks fine, @jesusff  we should correct `BoM`to `BOM`in [CMIP6_downscaling_plans.csv](https://github.com/WCRP-CORDEX/simulation-status/blob/main/CMIP6_downscaling_plans.csv)

**Comment by jesusff** [comment]
Looks fine, thank you @chunhsusu 

Just a small detail: in the [simulation status](https://wcrp-cordex.github.io/simulation-status/CMIP6_downscaling_plans.html?search.search=bom) it is currently written with lowercase "o": BoM. If you prefer all caps, we'll update the status website.

Also, please, update the expected completion date (or status) for this running simulation
https://github.com/WCRP-CORDEX/simulation-status/blob/01934da2a84ba7222aa518e6370ea99286c06c6c/CMIP6_downscaling_plans.csv#L43
which is already past.

**Comment by larsbuntemeyer** [comment]
In ESGF, i found `BOM` as an institution id, all capitals.

**Comment by gnikulin** [comment]
I also found that BOM was used in CORDEX-CMIP5

**Comment by jesusff** [comment]
I fixed this in the simulation plans. We can proceed to register. Let's see if this works...

/register

**Comment by jesusff** [comment]
/register

It didn't work 😉 . It has to be on the very first line...
