### ISSUE TITLE
source_id registration of BARPA-R1-NN

### ISSUE THREAD

**Issue by chunhsusu** [WCRP-CORDEX/cordex-cmip6-cv#45]
### label

BARPA-R1-NN

### label_extended

Bureau of Meteorology Atmospheric Regional Projections for Australia (BARPA) Regional Climate Model version 1 with Newtonian nudging

### source_id

BARPA-R1-NN

### source_type

ARCM

### release_year

2022

### activity_participation

DD

### institution_id

BOM

### further_info_url

http://www.bom.gov.au/research/publications/researchreports/BRR-069.pdf

### What license do you choose?

CC BY 4.0

**Comment by jesusff** [comment]
Thank you, @chunhsusu 

I wonder if you you want to make explicit the meaning of the "-R" in the label extended. We have in the [simulation status](https://wcrp-cordex.github.io/simulation-status/CMIP6_downscaling_plans.html?search.search=barra) also BARRA-R2 and BARRA-RE2 models. Do these regional reanalyses meet the CORDEX protocol? i.e are you planning to register them as well? Maybe we borrowed too much info from the original source for CORDEX-AUS (https://opus.nci.org.au/display/CMIP/CORDEX-CMIP6+datasets)

**Comment by chunhsusu** [comment]
Thanks @jesusff 

I can see the confusion and would like to make the following modifications to the original request:

- **source_id** = BARPA-R1-NN   (NB: the "-NN" follows the new CORDEX final spec)
- **source** = Bureau of Meteorology Atmospheric Regional Projections for Australia Regional Climate Model version 1 with Newtonian nudging   (NB: the "-R1" refers to RCM version 1)
- **label** = BARPA-R1-NN  (as with the source_id)

There is no plan to register or submit our reanalysis BARRAs to CORDEX. 

Let me know if further changes are needed.

**Comment by jesusff** [comment]
OK, thank you.

I updated the original post and also the [simulation status table](https://wcrp-cordex.github.io/simulation-status/CMIP6_downscaling_plans.html?search.search=barpa)

**Comment by jesusff** [comment]
/register

This one was pending and looks good
