### ISSUE TITLE
source_id registration of HadREM3-GA7-05

### ISSUE THREAD

**Issue by gredmond-mo** [WCRP-CORDEX/cordex-cmip6-cv#50]
### label

HadREM3-GA7-05

### label_extended

Hadley Centre Regional Model using Global Atmosphere version 7-05

### source_id

HadREM3-GA7-05

### source_type

ARCM

### release_year

2018

### activity_participation

DD

### institution_id

MOHC

### futher_info_url

https://view.es-doc.org/?renderMethod=id&project=cordexp&id=43837930-998b-4c0b-b481-f40b4884ddf1&version=1&client=esdoc-search

### What license do you choose?

CC BY 4.0

**Comment by jesusff** [comment]
Looks fine, thanks @gredmond-mo

**Comment by gnikulin** [comment]
fine as well
