### ISSUE TITLE
institution_id registration of CNRM-MF

### ISSUE THREAD

**Issue by pierrenabat** [WCRP-CORDEX/cordex-cmip6-cv#88]
### institution_id

CNRM-MF

### institution

CNRM [Centre National de Recherches Meteorologiques, Toulouse, France]; MF [Meteo France, Toulouse, France]

**Comment by jesusff** [comment]
Thank you. Would this be a single institution, such as a kind of division of CNRM, or more like an alliance for CORDEX, such as this example from CMIP6:

https://github.com/WCRP-CMIP/CMIP6_CVs/blob/2c9cf667546f31a495cb2e3b8d9d5892bc7abaa2/CMIP6_institution_id.json#L12

Regarding accented characters, we still have to make a decision (see #34) but, would "Meteorologiques" have some accents as well?

**Comment by pierrenabat** [comment]
CNRM-MF is a kind of alliance between CNRM and climate services of Meteo-France.
Yes there are accented characters, and the spelling for institution should be: CNRM (Centre National de Recherches Météorologiques) - MF (Météo France), Toulouse, France

**Comment by pierrenabat** [comment]
However we have some trouble with compression of netcdf files when we have accented characters in the netcdf attributes of the file, so we may remove them finally

**Comment by larsbuntemeyer** [comment]
In this case, i would suggest:
`institution: CNRM [Centre National de Recherches Meteorologiques, Toulouse, France]; MF [Meteo France, Toulouse, France]"`

**Comment by jesusff** [comment]
Yes, @larsbuntemeyer, I agree

**Comment by gnikulin** [comment]
fine for me
