### ISSUE TITLE
source_id registration of CRCM5

### ISSUE THREAD

**Issue by aulemahal** [WCRP-CORDEX/cordex-cmip6-cv#90]
### label

CRCM5-SN

### label_extended

Canadian Regional Climate Model version 5

### source_id

CRCM5-SN

### source_type

ARCM

### release_year

2015

### activity_participation

DD

### institution_id

OURANOS

### further_info_url

https://zenodo.org/doi/10.5281/zenodo.11061924

### What license do you choose?

CC BY 4.0

### More info
~We are planning on a Zenodo release (or something alike) for a preliminary public description of the model. I will update this issue as soon as we have a public url.~
EDIT: The Zenodo release has been added. The zenodo itself will be updated in the near future, this link points to the latest version.

**Comment by jesusff** [comment]
Thanks a lot for the input, Pascal.

Is this the exact same version as used in CORDEX CMIP5? The name matches. Note that in CORDEX-CMIP6 the model configuration cannot be distinguished by the `institution_id` (this happened in the past for CRCM5, check https://doi.org/10.5281/zenodo.6553526), nor by the `version_realization`. A different `source_id` should be registered for each configuration. Namely, if you plan to use spectral nudging:
> RCM simulations with spectral nudging must use the “SN” suffix in source_id (e.g. RCM123-SN)

**Comment by gnikulin** [comment]
It would be good to discuss with all groups that are going to use CRCM5 (e.g OURANOS and UQAM as in CORDEX-CMIP5) what CRCM5 configurations will be used and naming convention for them. Also `institution_id` must be registered together with `source_id`. If any kind of spectral nudging is used that should be reflected with "SN" suffix in `source_id` as mentioned above. No any problem to use exactly  the same version as in CORDEX-CMIP5.

**Comment by aulemahal** [comment]
Hi @jesusff and @gnikulin!

Indeed, we use spectral nudging, I updated the issue accordingly. And yes it is the same version as in CORDEX CMIP5.

As far as we know, UQAM is not going to submit simulations using the CRCM5 for CORDEX-CMIP6. Rather, their submissions will be done using the next version. We also plan to submit more simulations using that new version, using similar but not identical simulations. The tentative name of the new version is "CRCM6-GEM5-SN", but we will discuss with UQAM before registering this new sourche to make sure the distinction is reflected in the source id.

**Comment by larsbuntemeyer** [comment]
Related request is #41

**Comment by aulemahal** [comment]
Hi @larsbuntemeyer, I'm not sure what your comment means, but just in case: the CRCM5 and the CanRCM5 are two different models, even though their acronym resolves to the same name. They do have common parts, especially for the core atmospherical model, but they are being developed independently by different institutions.

**Comment by larsbuntemeyer** [comment]
Yes, @aulemahal thanks for the hint!

**Comment by aulemahal** [comment]
A `futher_info_url` has been added.

I discussed with colleagues and I realized the CanRCM5 and CRCM5 have even less in common than I previously thought. They do not share a core atmospherical model, contrary to what I first wrote above. So, same long name, different model, developed by different teams using different base parts.

**Comment by jesusff** [comment]
Perfect, thank you! I think this is ready to register. I rename then the [CRCM5 in the simulation status](https://wcrp-cordex.github.io/simulation-status/CMIP6_downscaling_plans.html?search.search=crcm5) to CRCM5-SN, right? since all those were run with spectral nudging

**Comment by aulemahal** [comment]
Exact, all CORDEX-targeted runs are using spectral nudging.

**Comment by gnikulin** [comment]
looks fine and can be registered
